name: dist-s1
channels:
  - conda-forge
dependencies:
  - python=>3.11 # required for shapely 2.0.0
  - pip
  # For packaging, and testing
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - jupyter
  - boto3
  - ipykernel
  - rasterio
  - geopandas
  - scikit-image
  - shapely=>2.0
  - pandas
  - tqdm
  - requests
  - rasterio
  - asf_search
  - earthaccess
  - tile_mate>=0.0.9
  - mpire
  - dem_stitcher
