name: dist-s1-intel
channels:
  - conda-forge
dependencies:
  - python=>3.11 # required for shapely 2.0.0
  - pip
  # For packaging, and testing
  - flake8
  - backoff
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - jupyter
  - contextily
  - boto3
  - ipykernel
  - rasterio
  - geopandas
  - scikit-image
  - shapely=>2.0
  - pandas
  - tqdm
  - requests
  - rasterio
  - asf_search
  - earthaccess
  - tile_mate>=0.0.9
  - mpire
  - dem_stitcher
  - leafmap
  - flask<3.0
  - localtileserver
  - dill
  - multiprocess
  - xarray
  - pytorch
  - torchvision
  - pytorch-lightning
  - kornia
  - pip:
     - torch
     - timm==0.4.12
     - torchmetrics
     - bm3d
     - git+https://github.com/opera-adt/DSWX-SAR.git
     - git+https://github.com/mhamilton723/FeatUp

